<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>RhythiaLib</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>whoswhip</Authors>
    <Description>A .NET 10 library for reading writing Rhythia files.</Description>
    <PackageProjectUrl>https://github.com/whoswhip/RhythiaLib</PackageProjectUrl>
    <PackageTags>parser;rhythia;rhr;encoder</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Copyright>MIT License</Copyright>
  </PropertyGroup>
  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
</Project>
